services:
  - type: web
    name: trademind-landing
    env: node
    rootDir: website
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
