services:
  - type: web
    name: trademind-waitlist
    env: node
    buildCommand: cd website && npm install && npm run build
    startCommand: cd website && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true
